name: Deploy Spotify API to EC2 via Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set version tag (Git SHA)
    - name: Set image tag
      run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

    # 3. Login to Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 4. Build versioned image
    - name: Build image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spotify-api:$TAG .

    # 5. Push versioned image
    - name: Push versioned image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spotify-api:$TAG

    # 6. Tag latest
    - name: Tag latest image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/spotify-api:$TAG \
                   ${{ secrets.DOCKER_USERNAME }}/spotify-api:latest

    # 7. Push latest
    - name: Push latest image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spotify-api:latest

    # 8. Deploy on EC2
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          echo "Logging into Docker Hub"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          echo "Pulling latest image"
          docker pull ${{ secrets.DOCKER_USERNAME }}/spotify-api:latest

          echo "Stopping old container"
          docker stop spotify-api-container || true
          docker rm spotify-api-container || true

          echo "Running new container"
          docker run -d \
            --name spotify-api-container \
            -p 8000:8000 \
            --restart unless-stopped \
            --env-file /home/ubuntu/app/.env \
            ${{ secrets.DOCKER_USERNAME }}/spotify-api:latest